apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-a8wx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-a8wx
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-a8wx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-a8wx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-a8wx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ddjz-tenant/rhtap-demo-app/hacbs-test-project-a8wx@sha256:babfa8b141346e7f9b79b31f252d261d7943bfc81b1e9ee94ef2f81a70675774
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
